version: '3.7'
services:
  server:
    image: "node:16"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - MONGO_URL=mongodb://user:9TF5KKZSu9kDQbxj@localhost/learnify
      - NODE_ENV=development
    volumes:
      - ./server/:/home/node/app
    expose:
      - "8081"
    ports:
      - "443:3000"
    command: "npm start"
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: learnify
    ports:
        - '27017:27017'
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js